# 🌐 LOCALIZATION VAULT - BLOCK 1: CORE CHANNELS (FULLY REMAPPED)
LOCALIZATION_VAULT = {
    "English": {
        "tab_explore": "🌐 Explore Universes", "tab_my_creations": "📂 My Creations", "tab_create": "🚀 Create a World", "tab_avatars": "🎭 Community Avatars", "tab_profile": "🔑 Account Profile", "status_control": "📡 STATUS CONTROL",
        "form_title": "### ⚔️ Universe Architect Form", "form_subtitle": "Tune the fundamental mechanics of your custom timeline before initializing the narrative seed.",
        "lbl_celestial": "##### 🪐 Celestial Physics", "lbl_name": "Universe Name:", "lbl_genre": "Select thematic genre:", "lbl_gravity": "🪐 Gravity Levels", "lbl_atmosphere": "💨 Atmospheric Density",
        "lbl_identity": "##### 🎭 Character Identity Settings", "lbl_char_name": "Your character's name:", "lbl_backstory": "Character profile/backstory:",
        "lbl_factions": "##### 🦅 Faction Architecture & Frictional Elements", "lbl_allies": "🦅 Dominant / Allied Faction Name", "lbl_enemies": "💀 Rogue / Opposing Faction Name", "lbl_directives": "✍️ Custom Environmental Directives / Constraints",
        "btn_deploy": "🚀 Deploy and Ignite Core Engine", "msg_success": "🎉 Custom universe timeline seed compiled successfully!",
        "genres": ["Sci-Fi", "Dark Fantasy", "Cyberpunk", "Horror", "Romance", "Other"],
        "atmosphere_options": ["Vacuum (Space)", "Thin / Toxic", "Breathable Baseline", "Hyper-Dense / Corrosive"],
        "trial_active": "⏳ TRIAL ACTIVE: {} Actions Left", "pool_depleted": "🔒 Action Pool Depleted!", "premium_pilot": "👑 PREMIUM PILOT AUTHENTICATED: {}",
        "active_records_title": "#### 👥 Active Community Records", "your_identity_title": "##### 👑 YOUR ACTIVE FORGED IDENTITY", "allied_dreamers_title": "##### 👥 ALLIED TIMELINE DREAMERS", "empty_ledger": "✨ The public ledger is currently empty. Be the first to forge a custom avatar identity asset above!", "signin_prompt": "🔑 Please sign in via the 'Account Profile' tab to view live character assets and authorize database ledger streams.",
        "dreamer_lbl": "Dreamer... {}", "music_prompt": "🎵 To listen to music, join or forge a world timeline", "unlimited_actions": "Want unlimited actions?", "btn_signin": "Sign In", "btn_signup": "Sign Up", "settings_control": "⚙️ Settings Control", "sub_genre_title": "🌌 Select Your Timeline Variant", "community_timeline_title": "📜 Public Community Timeline", "btn_join_world": "⚡ Enter This World Timeline",
        "auth_title": "### 🔑 Secure Identification Portal", "auth_subtitle": "Authorize your profile identity node to save custom timelines and clear limits.",
        "lbl_email": "Account Email Vector:", "lbl_pass": "Secure Password Signature:", "btn_login_submit": "🔐 Authorize Corridor Session", "btn_register_submit": "🚀 Forge New Profile Identity",
        "sub_genres_lbls": ["Sci-Fi", "Dark Fantasy", "Cyberpunk", "Horror", "Romance", "Other"],
        "btn_launch_scenario": "🎮 Launch Scenario",
        "settings_sub_status_title": "💳 Subscription Status",
        "settings_status_free": "⏳ STATUS: Free Trial Mode (12 Actions)",
        "settings_resync_title": "📡 Re-Sync Past Purchases",
        "settings_resync_desc": "Changed phones or reinstalled? Tap below to scan Stripe for your active billing cycle account profiles.",
        "settings_footer": "Haymaker Industry Security Architecture v1.02 • Privacy Framework Protected.",
        "hub_title": "🪐 Haymaker Industry Hub",
        "hub_subtitle": "Explore alternate realities or forge your own timeline",
        "profile_sync_lbl": "👑 Secure Profile Synchronized",
        "btn_logout_sidebar": "🚪 Log Out",
        "btn_logout_main": "🚪 Log Out of Platform Account",
        "forgot_pass_link": "❓ Forgot Password?",
        "forgot_pass_desc": "Enter your account email below to receive a secure terminal password reset link.",
        "btn_send_recovery": "🚀 Send Reset Token Link",
        "msg_recovery_sent": "📧 Secure reset token link dispatched to your inbox! Check your spam folder if it doesn't arrive in 60 seconds.",
        "legal_link": "⚖️ Terms of Service & Privacy Protection Policy",
        "legal_header": "Haymaker Industry End-User Terms & Privacy Charter",
        "legal_sec1_title": "1. Fictional Sandbox Waiver & Absolute Limitation of Liability",
        "legal_sec1_text": "Haymaker Industry operates strictly as an experimental, un-monitored, fictional text-sandbox simulator. All narrative text streams, character dialogue responses, and event tracking choices are 100% synthetic AI generation and completely fake. The platform, its core code infrastructure, and its independent developer hold absolute zero liability for user emotional distress, psychological attachment to fictional assets, or server data updates. Software maintenance may occur at any moment without warning, which can result in the structural resetting, degradation, or permanent erasure of saved world timelines. By passing this paywall, the user acknowledges that this environment is intrinsically unstable, accepts full responsibility for their psychological boundaries, and explicitly waives all rights to pursue legal claims or damages against the independent founder.",
        "legal_sec2_title": "2. Subscription Terms & Capital Refunding",
        "legal_sec2_text": "By submitting a credit card payment via our secure Stripe gateway, you are authorizing a recurring weekly billing pass subscription cycle ($4.99, $10.99, or $19.99 based on your selection). Due to immediate up-front OpenAI API data streaming costs generated by world initialization seeds, all subscription transactions are final and 100% non-refundable. Users hold full control and can terminate their recurring cycle via their personal Account Profile tab at any moment.",
        "legal_sec3_title": "3. Data Encryption & Profile Retention",
        "legal_sec3_text": "We respect user privacy and operate under an independent software sanctuary matrix. Your account email address, secure encrypted password signature, and saved custom universe timelines are securely mapped inside protected cloud database vaults. We do not sell, trade, or distribute your identity vector data to any corporate third-party networks or analytics engines."
    },
    "Español (Spanish)": {
        "tab_explore": "🌐 Explorar Universos", "tab_my_creations": "📂 Mis Creaciones", "tab_create": "🚀 Crear un Universo", "tab_avatars": "🎭 Avatares de la Comunidad", "tab_profile": "🔑 Perfil de Cuenta", "status_control": "📡 CONTROL DE ESTADO",
        "form_title": "### ⚔️ Formulario de Arquitecto del Universo", "form_subtitle": "Ajusta las mecánicas fundamentales de tu línea de tiempo antes de inicializar la semilla narrativa.",
        "lbl_celestial": "##### 🪐 Física Celestial", "lbl_name": "Nombre del Universo:", "lbl_genre": "Selecciona el género temático:", "lbl_gravity": "🪐 Niveles de Gravedad", "lbl_atmosphere": "💨 Densidad Atmosférica",
        "lbl_identity": "##### 🎭 Configuración de Identidad de Personaje", "lbl_char_name": "Nombre de tu personaje:", "lbl_backstory": "Perfil/Trasfondo del personaje:",
        "lbl_factions": "##### 🦅 Arquitetura de Facciones y Elementos de Fricción", "lbl_allies": "🦅 Nombre de la Facción Dominante / Aliada", "lbl_enemies": "💀 Nombre de la Facción Rebelde / Inimiga", "lbl_directives": "✍️ Diretrizes / Restrições Ambientais Personalizadas",
        "btn_deploy": "🚀 Implantar e Acender o Motor Central", "msg_success": "🎉 Semente da linha do tempo do universo compilada com sucesso!",
        "genres": ["Ficção Científica", "Fantasia Sombria", "Cyberpunk", "Terror", "Romance", "Outro"],
        "atmosphere_options": ["Vácuo (Espaço)", "Rara / Tóxica", "Linha de Base Respirável", "Hipertensa / Corrosiva"],
        "trial_active": "⏳ TESTE ATIVO: {} Ações Restantes", "pool_depleted": "🔒 Pool de Ações Esgotado!", "premium_pilot": "👑 PILOTO PREMIUM AUTENTICADO: {}",
        "active_records_title": "#### 👥 Registros Activos de la Comunidad", "your_identity_title": "##### 👑 SUA IDENTIDADE ATIVA FORJADA", "allied_dreamers_title": "##### 👥 SONHADORES DE LINHAS DO TEMPO ALIADAS", "empty_ledger": "✨ O registro público está atualmente vazio. Seja o primeiro a forjar uma identidade acima!", "signin_prompt": "🔑 Por favor, faça login na aba 'Perfil de Conta' para ver os registros dos personagens ao vivo.",
        "dreamer_lbl": "Sonhador... {}", "music_prompt": "🎵 Para ouvir música, junte-se ou forje uma linha do tempo mundial", "unlimited_actions": "Quer ações ilimitadas?", "btn_signin": "Entrar", "btn_signup": "Cadastrar-se", "settings_control": "⚙️ Controle de Configurações", "sub_genre_title": "🌌 Selecione Sua Variante de Linha do Tempo", "community_timeline_title": "📜 Linha do Tempo Pública da Comunidad", "btn_join_world": "⚡ Entrar Neste Universo da Comunidade",
        "auth_title": "### 🔑 Portal de Identificação Secure", "auth_subtitle": "Autorize seu nó de identidade de perfil para salvar linhas do tempo personalizadas.",
        "lbl_email": "E-mail da Conta:", "lbl_pass": "Senha de Segurança:", "btn_login_submit": "🔐 Autorizar Sessão", "btn_register_submit": "🚀 Forjar Nova Identidade de Perfil",
        "sub_genres_lbls": ["Ficção Científica", "Fantasia Sombria", "Cyberpunk", "Terror", "Romance", "Outro"],
        "btn_launch_scenario": "🎮 Iniciar Cenário",
        "settings_sub_status_title": "💳 Status da Assinatura",
        "settings_status_free": "⏳ STATUS: Modo de Teste Gratuitos (12 Ações)",
        "settings_resync_title": "📡 Re-sincronizar Compras Passadas",
        "settings_resync_desc": "Mudou de telefone ou reinstalou? Toque abaixo para escanear o Stripe em busca de perfis de conta com ciclo de faturamento ativo.",
        "settings_footer": "Arquitetura de Segurança da Haymaker Industry v1.02 • Estrutura de Privacidade Protegida.",
        "hub_title": "🪐 Hub Central da Haymaker Industry",
        "hub_subtitle": "Explore realidades alternativas ou forje a sua própria linha do tempo",
        "profile_sync_lbl": "👑 Perfil Seguro Sincronizado",
        "btn_logout_sidebar": "🚪 Sair",
        "btn_logout_main": "🚪 Sair da Conta da Plataforma",
        "forgot_pass_link": "❓ ¿Olvidaste tu contraseña?",
        "forgot_pass_desc": "Ingrese el correo electrónico de su cuenta a continuación para recibir un enlace seguro de restablecimiento de contraseña.",
        "btn_send_recovery": "🚀 Enviar enlace de restablecimiento",
        "msg_recovery_sent": "📧 ¡Enlace de restablecimiento seguro enviado a su bandeja de entrada! Revise su carpeta de correo no deseado si no llega en 60 segundos.",
        "legal_link": "⚖️ Términos de Servicio y Política de Protección de Privacidad",
        "legal_header": "Términos del Usuario Final y Estatuto de Privacidad de Haymaker Industry",
        "legal_sec1_title": "1. Renuncia del Entorno de Simulacro Fictício y Limitación Absoluta de Responsabilidad",
        "legal_sec1_text": "Haymaker Industry funciona estrictamente como un simulador de texto ficticio, experimental e no monitorado. Todas las transmisiones de texto narrativo, respuestas de diálogo de personajes y elecciones de seguimiento de eventos son 100% generation sintética de IA y totalmente falsas. La plataforma, la infraestructura de código central y su fundador independiente no asumen absolutamente ninguna responsabilidad por sufrimiento emocional del usuario, apego psicológico a activos ficticios o actualizaciones de datos del servidor. El mantenimiento del software puede ocurrir en cualquier momento sin previo aviso, lo que puede resultar en la redefinición estructural, degradación o eliminación permanente de las líneas de tiempo virtuales guardadas. Al pasar por este paywall, el usuario reconoce que este ambiente es intrínsecamente inestable, acepta total responsabilidad por sus límites psicológicos y renuncia explicientemente a todos los derechos de buscar reivindicaciones legales o daños contra el fundador independiente.",
        "legal_sec2_title": "2. Términos de Suscripción y Reembolso de Capital",
        "legal_sec2_text": "Al enviar un pago con tarjeta de crédito a través de nuestra pasarela segura de Stripe, está autorizando un ciclo de suscripción de pase de facturación semanal recurrente ($4.99, $10.99, o $19.99 según su selección). Debido a los costos de transmisión de datos de la API de OpenAI generados de inmediato por las sementes de inicialización del mundo, todas las transacciones de suscripción son definitivas y 100% no reembolsables. Los usuarios tienen control total y pueden rescindir su ciclo recurrente a través de su pestaña de Perfil de Conta personal en any momento.",
        "legal_sec3_title": "3. Cifrado de Datos y Retención de Perfiles",
        "legal_sec3_text": "Respetamos la privacidad del usuario y operamos bajo una matriz de santuario de software independiente. La dirección de correo electrónico de su cuenta, la firma de contraseña cifrada segura y las líneas de tiempo guardadas del universo personalizado están mapeadas de forma segura dentro de bóvedas de bases de datos protegidas en la nube. No vendemos, comercializan ni distribuimos los datos de su vector de identidade a ninguna red corporativa de terceros o motores de análisis."
    },
    "简体中文 (Mandarin)": {
        "tab_explore": "🌐 探索宇宙", "tab_my_creations": "📂 我的创作", "tab_create": "🚀 创造世界", "tab_avatars": "🎭 社区化身", "tab_profile": "🔑 账户个人资料", "status_control": "📡 状态控制",
        "form_title": "### 宇宙架构师表单", "form_subtitle": "在初始化叙事种子之前，调整自定义时间线的基础机制。",
        "lbl_celestial": "##### 🪐 天体物理学", "lbl_name": "宇宙名称:", "lbl_genre": "选择主题类型:", "lbl_gravity": "🪐 引力水平", "lbl_atmosphere": "💨 大气密度",
        "lbl_identity": "##### 🎭 角色身份设置", "lbl_char_name": "你的角色名称:", "lbl_backstory": "角色档案/背景故事:",
        "lbl_factions": "##### 🦅 阵营架构与摩擦元素", "lbl_allies": "🦅 主导/盟友阵营名称", "lbl_enemies": "💀 叛军/敌对阵营名称", "lbl_directives": "✍️ 自定义环境指令/限制",
        "btn_deploy": "🚀 部署并启动核心引擎", "msg_success": "🎉 自定义宇宙时间线种子成功编译！",
        "genres": ["科幻", "黑暗奇幻", "赛博朋克", "恐怖", "浪漫", "其他"],
        "atmosphere_options": ["真空 (太空)", "稀薄 / 有毒", "可呼吸基准线", "高密度 / 腐蚀性"],
        "trial_active": "⏳ 试用激活：剩余 {} 次操作", "pool_depleted": "🔒 操作次数已耗尽！", "premium_pilot": "👑 已认证的高级试点员：{}",
        "active_records_title": "#### 👥 活跃社区记录", "your_identity_title": "##### 👑 您当前处于激活状态的化身", "allied_dreamers_title": "##### 👥 盟友时间线追梦人", "empty_ledger": "✨ 公共账本目前为空。成为第一个在上方锻造自定义头像身份资产的人！", "signin_prompt": "🔑 请通过“账户个人资料”标签登录以查看实时角色资产并授权数据库账本流。",
        "dreamer_lbl": "追梦人... {}", "music_prompt": "🎵 要听音乐，请加入或打造 world 时间线", "unlimited_actions": "想要无限操作次数吗？", "btn_signin": "登录", "btn_signup": "注册", "settings_control": "⚙️ 设置控制", "sub_genre_title": "🌌 选择您的时间线变体", "community_timeline_title": "📜 公共社区时间线", "btn_join_world": "⚡ 进入此世界时间线",
        "auth_title": "### 🔑 安全身份验证门户", "auth_subtitle": "授权您的个人资料身份节点以保存自定义时间线并清除限制。",
        "lbl_email": "账户电子邮件:", "lbl_pass": "安全密码签名:", "btn_login_submit": "🔐 授权通道会话", "btn_register_submit": "🚀 锻造新个人身份",
        "sub_genres_lbls": ["科幻小说", "黑暗幻想", "赛博朋크", "恐怖", "浪漫", "其他"],
        "btn_launch_scenario": "🎮 启动场景",
        "settings_sub_status_title": "💳 订阅状态",
        "settings_status_free": "⏳ 状态：免费 trial 模式 (12 次操作)",
        "settings_resync_title": "📡 重新同步历史购买",
        "settings_resync_desc": "更换了手机或重新安装？点击下方扫描 Stripe 以获取您处于活跃计费周期的账户档案。",
        "settings_footer": "Haymaker Industry 安全架构 v1.02 • 隐私框架保护。",
        "hub_title": "🪐 Haymaker Industry 中心枢纽",
        "hub_subtitle": "探索交错现实或锻造属于您自己的时间线",
        "profile_sync_lbl": "👑 安全 profile 已同步",
        "btn_logout_sidebar": "🚪 退出登录",
        "btn_logout_main": "🚪 退出平台账户",
        "forgot_pass_link": "❓ 忘记密码？",
        "forgot_pass_desc": "在下方输入您的账户电子邮箱以获取安全的密码重置链接。",
        "btn_send_recovery": "🚀 发送重置链接",
        "msg_recovery_sent": "📧 安全重置链接已发送至您的收件箱！如果60秒内未收到，请检查垃圾邮件文件夹。",
        "legal_link": "⚖️ 服务条款与隐私保护政策",
        "legal_header": "Haymaker Industry 最终用户条款与隐私章程",
        "legal_sec1_title": "1. 虚拟沙盒豁免与绝对责任限制",
        "legal_sec1_text": "Haymaker Industry 严格作为一个实验性的、未受监控的虚拟文本沙盒模拟器运行。所有叙事文本流、角色对话回复和事件追踪选择均为100%人工智能合成生成，完全属于虚构。本平台、其核心代码基础设施以及独立创始人对用户的日常情绪波动、对虚拟资产 client 产生的心理依赖或服务器数据更新不承担任何绝对责任。软件维护可能在任何时间在不经预先通知的情况下发生，这可能导致保存的世界时间线遭到结构性重置、降级或永久清除。一经通过此付费墙，用户即承认该环境具有本质上的不稳定性，接受其全部心理边界的责任，并明确放弃对独立创始人追究法律诉讼或损害赔偿的权利。",
        "legal_sec2_title": "2. 订阅条款与资金退还说明",
        "legal_sec2_text": "通过我们安全的 Stripe 网关提交信用卡付款，即代表您授权了一个循环的每周计费通过订阅周期（根据您的选择为$4.99、$10.99或$19.99）。由于世界初始化种子立即产生了前置的 OpenAI API 数据流成本，所有订阅交易均为最终交易，且100%不可退款。用户拥有完全控制权，可随时通过个人“账户个人资料”标签页终止其循环周期。",
        "legal_sec3_title": "3. 组织数据加密与个人资料保留",
        "legal_sec3_text": "我们尊重用户隐私，并在一个独立的软件圣地矩阵下运行。您的账户电子邮箱地址、安全加密的密码签名以及保存的自定义宇宙时间线均安全地映射在受保护的云数据库金库中。我们绝不将您的身份向量数据出售、交易或分发给任何第三方公司网络或分析引擎。"
    }
}
# 🌐 LOCALIZATION VAULT - BLOCK 2: RUSSIAN, FRENCH, ARABIC EXPANSIONS
LOCALIZATION_VAULT.update({
    "Русский (Russian)": {
        "tab_explore": "🌐 Обзор Вселенных", "tab_my_creations": "📂 Мои Творения", "tab_create": "🚀 Создать Мир", "tab_avatars": "🎭 Аватары Сообщества", "tab_profile": "🔑 Профиль Аккаунта", "status_control": "📡 МОНИТОР СТАТУСА",
        "form_title": "### ⚔️ Форма Архитектора Вселенной", "form_subtitle": "Настройте фундаментальную механику вашей временной шкалы перед запуском повествовательного семени.",
        "lbl_celestial": "##### 🪐 Небесная Физика", "lbl_name": "Название Вселенной:", "lbl_genre": "Выберите жанр:", "lbl_gravity": "🪐 Уровни Гравитации", "lbl_atmosphere": "💨 Плотность Атмосферы",
        "lbl_identity": "##### 🎭 Настройки Личности Персонажа", "lbl_char_name": "Имя вашего персонажа:", "lbl_backstory": "Профиль/Биография персонажа:",
        "lbl_factions": "##### 🦅 Архитектура Фракций и Элементы Трения", "lbl_allies": "🦅 Имя Доминирующей Фракции", "lbl_enemies": "💀 Имя Враждебной Фракции", "lbl_directives": "✍️ Особые Директивы и Ограничения Мира",
        "btn_deploy": "🚀 Развернуть и Запустить Ядро", "msg_success": "🎉 Семя вселенной успешно скомпилировано!",
        "genres": ["Фантастика", "Темное Фэнтези", "Киберпанк", "Хоррор", "Романтика", "Другое"],
        "atmosphere_options": ["Вакуум (Космос)", "Тонкая / Токсичная", "Дыхательный Базис", "Плотная / Коррозийная"],
        "trial_active": "⏳ ПРОБНЫЙ ПЕРИОД: Осталось {} действий", "pool_depleted": "🔒 Пакет действий исчерпан!", "premium_pilot": "👑 ПРЕМИУМ-ПИЛОТ АВТОРИЗОВАН: {}",
        "active_records_title": "#### 👥 Активные Записи Сообщества", "your_identity_title": "##### 👑 ВАШ АКТИВНЫЙ АВАТАР", "allied_dreamers_title": "##### 👥 СОЮЗНЫЕ СТРАННИКИ ВРЕМЕНИ", "empty_ledger": "✨ Публичный реестр пуст.", "signin_prompt": "🔑 Пожалуйста, войдите в аккаунт.",
        "dreamer_lbl": "Мечтатель... {}", "music_prompt": "🎵 Чтобы слушать музыку, войдите в мир", "unlimited_actions": "Хотите безлимит?", "btn_signin": "Войти", "btn_signup": "Регистрация", "settings_control": "⚙️ Настройки", "sub_genre_title": "🌌 Выберите вариант временной шкалы", "community_timeline_title": "📜 Публичная хроника сообщества", "btn_join_world": "⚡ Войти в этот мир",
        "auth_title": "### 🔑 Безопасный портал идентификации", "auth_subtitle": "Авторизуйте свой идентификационный узел.",
        "lbl_email": "Электронная почта:", "lbl_pass": "Пароль:", "btn_login_submit": "🔐 Авторизовать сессию коридора", "btn_register_submit": "🚀 Создать новый профиль",
        "sub_genres_lbls": ["Научная фантастика", "Темное фэнтези", "Киберпанк", "Ужасы", "Романтика", "Другое"],
        "btn_launch_scenario": "🎮 Запустить сценарий",
        "settings_sub_status_title": "💳 Статус подписки",
        "settings_status_free": "⏳ СТАТУС: Режим бесплатной версии (12 действий)",
        "settings_resync_title": "📡 Синхронизация прошлых покупок",
        "settings_resync_desc": "Поменяли телефон или переустановили? Нажмите ниже, чтобы отсканировать Stripe на наличие активных профилей биллинга.",
        "settings_footer": "Архитектура безопасности Haymaker Industry v1.02 • Защищено структурой конфиденциальности.",
        "hub_title": "🪐 Главный хаб Haymaker Industry",
        "hub_subtitle": "Исследуйте альтернативные реальности или создайте свою временную шкалу",
        "profile_sync_lbl": "👑 Безопасный профиль синхронизирован",
        "btn_logout_sidebar": "🚪 Выйти",
        "btn_logout_main": "🚪 Выйти из аккаунта платформы",
        "forgot_pass_link": "❓ Забыли пароль?",
        "forgot_pass_desc": "Введите адрес электронной почты вашего аккаунта ниже, чтобы получить безопасную ссылку для сброса пароля.",
        "btn_send_recovery": "🚀 Отправить ссылку для сброса",
        "msg_recovery_sent": "📧 Безопасная ссылка для сброса отправлена на ваш почтовый ящик! Если письмо не пришло в течение 60 секунд, проверьте папку со спамом.",
        "legal_link": "⚖️ Условия использования и политика защиты конфиденциальности",
        "legal_header": "Условия использования для конечных пользователей и Хартия конфиденциальности Haymaker Industry",
        "legal_sec1_title": "1. Отказ от ответственности за вымышленную песочницу и абсолютное ограничение ответственности",
        "legal_sec1_text": "Haymaker Industry работает строго как экспериментальный, неконтролируемый, вымышленный симулятор текстовой песочницы. Все потоки повествовательного текста, ответы персонажей и варианты отслеживания событий на 100% генерируются искусственным интеллектом и являются полностью вымышленными. Платформа, ее базовая кодовая инфраструктура и независимый разработчик не несут абсолютно никакой ответственности за эмоциональные переживания пользователя, психологическую привязанность к виртуальным объектам или обновления данных на сервере. Техническое обслуживание программного обеспечения может произойти в любой момент без предварительного уведомления, что может привести к структурному сбросу, деградации или безвозвратному удалению сохраненных временных шкал мира. Проходя этот платежный шлюз, пользователь подтверждает, что данная среда по своей природе нестабильна, принимает на себя полную ответственность за свои психологические границы и явно отказывается от всех прав на преследование судебных исков или возмещение ущерба против независимого основателя.",
        "legal_sec2_title": "2. Условия подписки и возврат средств",
        "legal_sec2_text": "Отправляя платеж по кредитной карте через наш безопасный шлюз Stripe, вы разрешаете регулярный еженедельный цикл подписки (4.99, 10.99 или 19.99 долларов США в зависимости от вашего выбора). Из-за немедленных первоначальных затрат на потоковую передачу данных API OpenAI, вызванных инициализацией мира, все транзакции по подписке являются окончательными и на 100% не подлежат возврату. Пользователи сохраняют полный контроль и могут прекратить свой регулярный цикл через личную вкладку «Профиль аккаунта» в любой момент.",
        "legal_sec3_title": "3. Шифрование данных и сохранение профиля",
        "legal_sec3_text": "Мы уважаем конфиденциальность пользователей и работаем в рамках независимой защищенной матрицы программного обеспечения. Адрес электронной почты вашего аккаунта, безопасная зашифрованная подпись пароля и сохраненные временные шкалы пользовательских вселенных надежно сопоставлены внутри защищенных облачных хранилищ баз данных. Мы не продаем, не обмениваем и не распространяем данные вашего идентификатора сторонним корпоративным сетям или аналитическим системам."
    },
    "Français (French)": {
        "tab_explore": "🌐 Explorer les Univers", "tab_my_creations": "📂 Mes Créations", "tab_create": "🚀 Créer un Monde", "tab_avatars": "🎭 Avatares de la Communauté", "tab_profile": "🔑 Profil du Compte", "status_control": "📡 CONTRÔLE DE STATUT",
        "form_title": "### ⚔️ Formulaire d'Architecte d'Univers", "form_subtitle": "Ajustez les mécaniques fondamentales de votre chronologie avant d'initialiser le code narratif.",
        "lbl_celestial": "##### 🪐 Physique Céleste", "lbl_name": "Nom de l'Univers:", "lbl_genre": "Sélectionnez le genre:", "lbl_gravity": "🪐 Niveaux de Gravité", "lbl_atmosphere": "💨 Densité Atmosphérique",
        "lbl_identity": "##### 🎭 Paramètres d'Identité du Personnage", "lbl_char_name": "Nom de votre personnage:", "lbl_backstory": "Profil/Histoire du personnage:",
        "lbl_factions": "##### 🦅 Architecture des Factions & Éléments de Friction", "lbl_allies": "🦅 Nom de la Faction Dominante / Alliée", "lbl_enemies": "💀 Nom de la Faction Ennemie", "lbl_directives": "✍️ Directives / Contraintes Environnementales Spécifiques",
        "btn_deploy": "🚀 Déployer et Activer le Moteur Central", "msg_success": "🎉 Le code de l'univers a été compilé avec succès !",
        "genres": ["Sci-Fi", "Dark Fantasy", "Cyberpunk", "Horreur", "Romance", "Autre"],
        "atmosphere_options": ["Vide (Espace)", "Mince / Toxique", "Atmosphère Respirable", "Hyper-Dense / Corrosive"],
        "trial_active": "⏳ ESSAI ACTIF: {} Actions Restantes", "pool_depleted": "🔒 Pool d'Actions Épuisé !", "premium_pilot": "👑 PILOTE PREMIUM AUTHENTIFIÉ: {}",
        "active_records_title": "#### 👥 Registres Actifs de la Communauté", "your_identity_title": "##### 👑 VOTRE IDENTITÉ ACTIVE", "allied_dreamers_title": "##### 👥 REVEURS CHRONOLOGIQUES ALLIÉS", "empty_ledger": "✨ Le registre public est vide.", "signin_prompt": "🔑 Veuillez vous connecter pour voir les enregistrements.",
        "dreamer_lbl": "Rêveur... {}", "music_prompt": "🎵 Pour écouter de la musique, rejoignez un monde", "unlimited_actions": "Actions illimitées ?", "btn_signin": "Connexion", "btn_signup": "S'inscrire", "settings_control": "⚙️ Réglages", "sub_genre_title": "🌌 Sélectionnez votre variante", "community_timeline_title": "📜 Chronologie publique", "btn_join_world": "⚡ Rejoindre ce monde",
        "auth_title": "### 🔑 Portail d'Identification Séquentiel Sécurisé", "auth_subtitle": "Autorisez votre nœud d'identité pour sauvegarder vos univers.",
        "lbl_email": "Email du Compte:", "lbl_pass": "Mot de Passe Sécurisé:", "btn_login_submit": "🔐 Autoriser la Session", "btn_register_submit": "🚀 Forger une Nouvelle Identité",
        "sub_genres_lbls": ["Sci-Fi", "Dark Fantasy", "Cyberpunk", "Horreur", "Romance", "Autre"],
        "btn_launch_scenario": "🎮 Lancer le Scénario",
        "settings_sub_status_title": "💳 Statut de l'Abonnement",
        "settings_status_free": "⏳ STATUT : Mode d'Essai Gratuit (12 Actions)",
        "settings_resync_title": "📡 Re-synchroniser les Achats Passés",
        "settings_resync_desc": "Changement de téléphone ou réinstallation ? Appuyez ci-dessous pour scanner Stripe pour vos profils de compte de cycle de facturation actifs.",
        "settings_footer": "Architecture de Securité de Haymaker Industry v1.02 • Cadre de Confidentialité Protégé.",
        "hub_title": "🪐 Hub Central de Haymaker Industry",
        "hub_subtitle": "Explorez des réalités alternatives ou forgez votre propre chronologie",
        "profile_sync_lbl": "👑 Profil Sécurisé Synchronisé",
        "btn_logout_sidebar": "🚪 Se Déconnecter",
        "btn_logout_main": "🚪 Se Déconnecter du Compte de la Plateforme",
        "forgot_pass_link": "❓ Mot de passe oublié ?",
        "forgot_pass_desc": "Saisissez l'adresse e-mail de votre compte ci-dessous pour recevoir un lien de réinitialisation sécurisé.",
        "btn_send_recovery": "🚀 Envoyer le lien de réinitialisation",
        "msg_recovery_sent": "📧 Un lien de réinitialisation sécurisé a été envoyé dans votre boîte de réception ! Vérifiez vos spams s'il n'arrive pas dans les 60 secondes.",
        "legal_link": "⚖️ Conditions d'utilisation et politique de confidentialité",
        "legal_header": "Conditions d'utilisation et charte de confidentialité de Haymaker Industry",
        "legal_sec1_title": "1. Exonération relative au bac à sable fictif et limitation absolue de responsabilité",
        "legal_sec1_text": "Haymaker Industry fonctionne strictement comme un simulateur expérimental, non surveillé et fictif de bac à sable textuel. Tous les flux de textes narratifs, les réponses de dialogue des personnages et les choix de suivi des événements sont générés à 100 % par une IA synthétique et sont totalement fictifs. La plateforme, son infrastructure de code de base et son développeur indépendant n'assument absolument aucune responsabilité en cas de détresse émotionnelle de l'utilisateur, d'attachement psychologique à des éléments fictifs ou de mises à jour des données du serveur. Des opérations de maintenance logicielle peuvent survenir à tout moment et sans préavis, ce qui peut entraîner la réinitialisation structurelle, la dégradation ou l'effacement permanent des chronologies des mondes sauvegardés. En franchissant ce paywall, l'utilisateur reconnaît que cet environnement est intrinsèquement instable, accepte l'entière responsabilité de ses propres limites psychologiques et renonce explicitement à tout droit d'engager des poursuites judiciaires ou de réclamer des dommages-intérêts à l'encontre du fondateur indépendant.",
        "legal_sec2_title": "2. Conditions d'abonnement et non-remboursement",
        "legal_sec2_text": "En soumettant un paiement par carte bancaire via notre passerelle sécurisée Stripe, vous autorisez un cycle d'abonnement hebdomadaire récurrent (4.99 $, 10.99 $ ou 19.99 $ selon votre sélection). En raison des coûts immédiats et initiaux de streaming de données de l'API OpenAI générés par les codes d'initialisation du monde, toutes les transactions d'abonnement sont définitives et 100 % non remboursables. Les utilisateurs conservent un contrôle total et peuvent mettre fin à leur cycle récurrent via leur onglet Profil du Compte à tout moment.",
        "legal_sec3_title": "3. Chiffrement des données et conservation des profils",
        "legal_sec3_text": "We respect user privacy and operate under an independent software sanctuary matrix. Your account email address, secure encrypted password signature, and saved custom universe timelines are securely mapped inside protected cloud database vaults. We do not sell, trade, or distribute your identity vector data to any corporate third-party networks or analytics engines."
    },
    "العربية (Arabic)": {
        "tab_explore": "🌐 استكشاف العوالم", "tab_my_creations": "📂 إبداعاتي", "tab_create": "🚀 صنع عالمًا", "tab_avatars": "🎭 شخصيات المجتمع", "tab_profile": "🔑 ملف الحساب", "status_control": "📡 مراقبة الحالة",
        "form_title": "### ⚔️ نموذج مهندس الكون", "form_subtitle": "قم بضبط الآليات الأساسية لخطك الزمني قبل تهيئة النواة السردية.",
        "lbl_celestial": "##### 🪐 الفيزياء الفلكية", "lbl_name": "اسم الكون:", "lbl_genre": "اختر نوع القصة:", "lbl_gravity": "🪐 مستويات الجاذبية", "lbl_atmosphere": "💨 كثافة الغلاف الجوي",
        "lbl_identity": "##### 🎭 إعدادات هوية الشخصية", "lbl_char_name": "اسم شخصيتك:", "lbl_backstory": "ملف الشخصية / الخلفية الدرامية:",
        "lbl_factions": "##### 🦅 بنية الفصائل وعناصر الاحتكاك", "lbl_allies": "🦅 اسم الفصيل الحليف / المسيطر", "lbl_enemies": "💀 اسم الفصيل المعادي", "lbl_directives": "✍️ توجيهات وقيود بيئية مخصصة",
        "btn_deploy": "🚀 نشر وتفعيل المحرك الرئيسي", "msg_success": "🎉 تم تجميع نواة الكون المخصص بنجاح!",
        "genres": ["خيال علمي", "فانتازيا مظلمة", "سايبربانك", "رعب", "رومانسي", "آخر"],
        "atmosphere_options": ["فراغ (الفضاء)", "رقيق / سام", "قابل للتنفس", "كثيف جدًا / أكّال"],
        "trial_active": "⏳ الفترة التجريبية: متبقي {} إجراءات", "pool_depleted": "🔒 تم استنفاد رصيد الإجراءات!", "premium_pilot": "👑 تم التحقق من الطيار المتميز: {}",
        "active_records_title": "#### 👥 سجلات المجتمع推力", "your_identity_title": "##### 👑 هويتك النشطة الحالية", "allied_dreamers_title": "##### 👥 الحالمون في الخطوط الزمنية الحليفة", "empty_ledger": "✨ السجل العام فارغ حاليًا.", "signin_prompt": "🔑 يرجى تسجيل الدخول لعرض السجلات.",
        "dreamer_lbl": "الحالم... {}", "music_prompt": "🎵 للاستماع للموسيقى，انضم لعالم", "unlimited_actions": "تريد إجراءات غير محدودة؟", "btn_signin": "تسجيل الدخول", "btn_signup": "إنشاء حساب", "settings_control": "⚙️ التحكم بالإعدادات", "sub_genre_title": "🌌 اختر بديل الخط الزمني", "community_timeline_title": "📜 الخط الزمني العام للمجتمع", "btn_join_world": "⚡ دخول هذا الخط الزمني",
        "auth_title": "### 🔑 بوابة التحقق الآمنة", "auth_subtitle": "قم بترخيص معرفك الشخصي لحفظ الخطوط الزمنية وتخطي القيود.",
        "lbl_email": "البريد الإلكتروني:", "lbl_pass": "كلمة المرور الآمنة:", "btn_login_submit": "🔐 ترخيص جلسة الممر", "btn_register_submit": "🚀 إنشاء هوية جديدة",
        "sub_genres_lbls": ["خيال علمي", "فانتازيا مظلمة", "سايبربانك", "رعب", "رومانسي", "آخر"],
        "btn_launch_scenario": "🎮 بدء السيناريو",
        "settings_sub_status_title": "💳 حالة الاشتراك",
        "settings_status_free": "⏳ الحالة: وضع الفترة التجريبية المجانية (12 إجراء)",
        "settings_resync_title": "📡 إعادة مزامنة المشتريات السابقة",
        "settings_resync_desc": "هل قمت بتغيير هاتفك أو إعادة التثبيت؟ اضغط أدناه لمسح Stripe بحثًا عن ملفات تعريف حساب دورة الفوترة النشطة.",
        "settings_footer": "بنية Haymaker Industry الأمنية إصدار v1.02 • إطار الخصوصية المحمي.",
        "hub_title": "🪐 مركز Haymaker Industry الرئيسي",
        "hub_subtitle": "استكشف العوالم البديلة أو اصنع خطك الزمني الخاص",
        "profile_sync_lbl": "👑 تم مزامنة الملف الشخصي الآمن",
        "btn_logout_sidebar": "🚪 تسجيل الخروج",
        "btn_logout_main": "🚪 تسجيل الخروج من حساب المنصة",
        "forgot_pass_link": "❓ هل نسيت كلمة المرور؟",
        "forgot_pass_desc": "أدخل البريد الإلكتروني لحسابك أدناه لتلقي رابط آمن لإعادة تعيين كلمة المرور الخاصة بك.",
        "btn_send_recovery": "🚀 إرسال رابط إعادة التعيين",
        "msg_recovery_sent": "📧 تم إرسال رابط إعادة التعيين الآمن إلى صندوق الوارد الخاص بك! تحقق من مجلد البريد العشوائي إذا لم يصل خلال 60 ثانية.",
        "legal_link": "⚖️ شروط الخدمة وسياسة حماية الخصوصية",
        "legal_header": "شروط المستخدم النهائي وميثاق الخصوصية لشركة Haymaker Industry",
        "legal_sec1_title": "1. إخلاء مسؤولية البيئة الافتراضية والحد المطلق للمسؤولية",
        "legal_sec1_text": "تعمل منصة Haymaker Industry بشكل صارم كمحاكي تجريبي غير مراقب لعوالم النصوص الافتراضية. جميع التدفقات السردية، حوارات الشخصيات، وخيارات تتبع الأحداث هي إنتاج اصطناعي بنسبة 100% بواسطة الذكاء الاصطناعي وهي خيالية بالكامل. لا تتحمل المنصة، بنيتها التحتية البرمجية، أو مطورها المستقل أي مسؤولية مطلقة عن الضيق العاطفي للمستخدم, الارتباط النفسي بالأصول الخيالية، أو تحديثات خادم البيانات. قد تحدث صيانة البرمجيات في أي وقت دون سابق إنذار، مما قد يؤدي إلى إعادة ضبط هيكلية للخطوط الزمنية المحفوظة أو تدهورها أو مسحها نهائيًا. بتخطي جدار الدفع هذا، يقر المستخدم بأن هذه البيئة غير مستقرة بطبيعتها، ويتحمل المسؤولية الكاملة عن حدوده النفسية، ويتنازل صراحةً عن جميع الحقوق في الملاحقة القضائية أو المطالبة بالتعويضات ضد المؤسس المستقل.",
        "legal_sec2_title": "2. شروط الاشتراك وعدم قابلية الاسترداد",
        "legal_sec2_text": "عبر إرسال الدفع ببطاقة الائتمان من خلال بوابة Stripe الآمنة، فإنك توافق على تفعيل دورة اشتراك أسبوعية متكررة (بقيمة 4.99 أو 10.99 أو 19.99 دولارًا بناءً على اختيارك). ونظرًا للتكاليف الفورية والمسبقة لتدفق بيانات واجهة برمجة تطبيقات OpenAI الناتجة عن إنشاء العوالم، فإن جميع معاملات الاشتراك نهائية وغير قابلة للاسترداد بنسبة 100%. يحتفظ المستخدمون بالتحكم الكامل ويمكنهم إنهاء دورة الاشتراك في أي وقت عبر تبويب ملف الحساب الشخصي.",
        "legal_sec3_title": "3. تشفير البيانات والاحتفاظ بملف التعريف",
        "legal_sec3_text": "نحن نحترم خصوصية المستخدم ونعمل تحت مظلة أمنية برمجية مستقلة. يتم تخزين البريد الإلكتروني لحسابك، توقيع كلمة المرور المشفرة الآمنة، والخطوط الزمنية المحفوظة لعوالمك المخصصة بشكل آمن داخل قواعد بيانات سحابية محمية. نحن لا نبيع أو نتاجر أو نوزع بيانات هويتك الشخصية لأي شبكات شركات خارجية أو محركات تحليل."
    }
})
# 🌐 LOCALIZATION VAULT - BLOCK 3: HINDI, JAPANESE, KOREAN ASIA POWERHOUSES
LOCALIZATION_VAULT.update({
    "हिन्दी (Hindi)": {
        "tab_explore": "🌐 ब्रह्मांड खोजें", "tab_my_creations": "📂 मेरी रचनाएँ", "tab_create": "🚀 ब्रह्मांड बनाएं", "tab_avatars": "🎭 समुदाय अवतार", "tab_profile": "🔑 खाता प्रोफ़ाइल", "status_control": "📡 स्थिति नियंत्रण",
        "form_title": "### ⚔️ ब्रह्मांड आर्किटेक्ट फॉर्म", "form_subtitle": "कथा बीज शुरू करने से पहले अपनी समयरेखा के बुनियादी तंत्र को ट्यून करें.",
        "lbl_celestial": "##### 🪐 खगोलीय भौतिकी", "lbl_name": "ब्रह्मांड का नाम:", "lbl_genre": "शैली चुनें:", "lbl_gravity": "🪐 गुरुत्वाकर्षण स्तर", "lbl_atmosphere": "💨 वायुमंडलीय घनत्व",
        "lbl_identity": "##### 🎭 चरित्र पहचान सेटिंग्स", "lbl_char_name": "आपके चरित्र का नाम:", "lbl_backstory": "चरित्र प्रोफ़ाइल:",
        "lbl_factions": "##### 🦅 गुट वास्तुकला", "lbl_allies": "🦅 प्रमुख गुट का नाम", "lbl_enemies": "💀 विरोधी गुट का नाम", "lbl_directives": "✍️ कस्टम निर्देश",
        "btn_deploy": "🚀 कोर इंजन तैनात करें", "msg_success": "🎉 ब्रह्मांड समयरेखा सफलतापूर्वक संकलित की गई!",
        "genres": ["साइंस-फिक्शन", "डार्क फंतासी", "साइबरपंक", "हॉरर", "रोमांस", "अन्य"],
        "atmosphere_options": ["वैक्यूम (अंतरिक्ष)", "पतली / जहरीली", "सांस लेने योग्य", "अत्यधिक घनी"],
        "trial_active": "⏳ परीक्षण सक्रिय: {} क्रियाएं शेष", "pool_depleted": "🔒 क्रिया पूल समाप्त!", "premium_pilot": "👑 प्रीमियम पायलट प्रमाणित: {}",
        "active_records_title": "#### 👥 सक्रिय समुदाय रिकॉर्ड", "your_identity_title": "##### 👑 आपकी सक्रिय पहचान", "allied_dreamers_title": "##### 👥 संबद्ध सपने देखने वाले", "empty_ledger": "✨ सार्वजनिक खाता खाली है.", "signin_prompt": "🔑 कृपया रिकॉर्ड देखने के लिए लॉग इन करें.",
        "dreamer_lbl": "सपने देखने वाला... {}", "music_prompt": "🎵 संगीत सुनने के लिए, ब्रह्मांड से जुड़ें", "unlimited_actions": "असीमित क्रियाएं चाहिए?", "btn_signin": "लॉग इन करें", "btn_signup": "साइन अप करें", "settings_control": "⚙️ सेटिंग्स नियंत्रण", "sub_genre_title": "🌌 अपना समयरेखा संस्करण चुनें", "community_timeline_title": "📜 सार्वजनिक समुदाय समयरेखा", "btn_join_world": "⚡ इस ब्रह्मांड में प्रवेश करें",
        "auth_title": "### 🔑 सुरक्षित पहचान पोर्टल", "auth_subtitle": "अपनी प्रोफ़ाइल पहचान को अधिकृत करें.",
        "lbl_email": "खाता ईमेल:", "lbl_pass": "सुरक्षित पासवर्ड:", "btn_login_submit": "🔐 कॉरिडोर सत्र अधिकृत करें", "btn_register_submit": "🚀 नई पहचान का निर्माण करें",
        "sub_genres_lbls": ["साइंस-फिक्शन", "डार्क फंतासी", "साइबरपंक", "हॉरर", "रोमांस", "अन्य"],
        "btn_launch_scenario": "🎮 परिदृश्य लॉन्च करें",
        "settings_sub_status_title": "💳 सदस्यता की स्थिति",
        "settings_status_free": "⏳ स्थिति: मुफ़्त परीक्षण मोड (12 क्रियाएं)",
        "settings_resync_title": "📡 पिछली खरीदारी को पुन: सिंक करें",
        "settings_resync_desc": "फोन बदल दिया या फिर से इंस्टॉल किया? अपने सक्रिय बिलिंग चक्र खाता प्रोफाइल के लिए स्ट्राइप को स्कैन करने के लिए नीचे टैप करें।",
        "settings_footer": "Haymaker Industry सुरक्षा आर्किटेक्चर v1.02 • गोपनीयता ढांचा सुरक्षित।",
        "hub_title": "🪐 Haymaker Industry मुख्य हब",
        "hub_subtitle": "वैकल्पिक वास्तविकताओं का पता लगाएं या अपनी खुद की समयरेखा बनाएं",
        "profile_sync_lbl": "👑 सुरक्षित प्रोफ़ाइल सिंक्रनाइज़",
        "btn_logout_sidebar": "🚪 लॉग आउट",
        "btn_logout_main": "🚪 प्लेटफ़ॉर्म खाते से लॉग आउट करें",
        "forgot_pass_link": "❓ पासवर्ड भूल गए?",
        "forgot_pass_desc": "सुरक्षित पासवर्ड रीसेट लिंक प्राप्त करने के लिए नीचे अपने खाते का ईमेल दर्ज करें।",
        "btn_send_recovery": "🚀 रीसेट लिंक भेजें",
        "msg_recovery_sent": "📧 सुरक्षित रीसेट लिंक आपके इनबॉक्स में भेज दिया गया है! यदि यह 60 सेकंड में नहीं आता है, तो अपना स्पैम फ़ोल्डर जांचें।",
        "legal_link": "⚖️ सेवा की शर्तें और गोपनीयता नीति",
        "legal_header": "Haymaker Industry अंतिम उपयोगकर्ता शर्तें और गोपनीयता चार्टर",
        "legal_sec1_title": "1. काल्पनिक सैंडबॉक्स छूट और पूर्ण देयता सीमा",
        "legal_sec1_text": "Haymaker Industry कड़ाई से एक प्रयोगात्मक, बिना निगरानी वाले, काल्पनिक पाठ-सैंडबॉक्स सिम्युलेटर के रूप में काम करती है। सभी कथा पाठ धाराएं, चरित्र संवाद प्रतिक्रियाएं और घटना ट्रैकिंग विकल्प 100% सिंथेटिक एआई पीढ़ी हैं और पूरी तरह से नकली हैं। यह प्लेटफ़ॉर्म, इसका मुख्य कोड बुनियादी ढांचा, और इसके स्वतंत्र संस्थापक उपयोगकर्ता के भावनात्मक संकट, काल्पनिक संपत्तियों के प्रति मनोवैज्ञानिक लगाव या सर्वर डेटा अपडेट के लिए पूर्ण शून्य दायित्व रखते हैं। सॉफ्टवेयर रखरखाव बिना किसी पूर्व चेतावनी के किसी भी समय हो सकता है, जिसके परिणामस्वरूप सहेजी गई विश्व समयरेखाओं को संरचनात्मक रूप से रीसेट, खराब या स्थायी रूप से मिटाया जा सकता है। इस पेवॉल को पार करके, उपयोगकर्ता स्वीकार करता है कि यह वातावरण स्वाभाविक रूप से अस्थिर है, अपनी मनोवैज्ञानिक सीमाओं के लिए पूरी जिम्मेदारी स्वीकार करता है, और स्पष्ट रूप से स्वतंत्र संस्थापक के खिलाफ कानूनी दावों या नुकसान का पीछा करने के सभी अधिकारों को छोड़ देता है।",
        "legal_sec2_title": "2. सदस्यता शर्तें और गैर-वापसी नीति",
        "legal_sec2_text": "हमारे सुरक्षित स्ट्राइप गेटवे के माध्यम से क्रेडिट कार्ड भुगतान सबमिट करके, आप एक आवर्ती साप्ताहिक बिलिंग पास सदस्यता चक्र ($4.99, $10.99, या $19.99 आपके चयन के आधार पर) को अधिकृत कर रहे हैं। विश्व आरंभीकरण बीजों द्वारा उत्पन्न तत्काल अग्रिम OpenAI API डेटा स्ट्रीमिंग लागतों के कारण, सभी सदस्यता लेनदेन अंतिम हैं और 100% गैर-वापसीयोग्य हैं। उपयोगकर्ता पूर्ण नियंत्रण रखते हैं और किसी भी समय अपने व्यक्तिगत खाता प्रोफ़ाइल टैब के माध्यम से अपने आवर्ती चक्र को समाप्त कर सकते हैं।",
        "legal_sec3_title": "3. डेटा एन्क्रिप्शन और प्रोफ़ाइल अवधारण",
        "legal_sec3_text": "हम उपयोगकर्ता की गोपनीयता का सम्मान करते हैं और एक स्वतंत्र सॉफ़्टवेयर अभयारण्य मैट्रिक्स के तहत काम करते हैं। आपका खाता ईमेल पता, सुरक्षित एन्क्रिप्टेड पासवर्ड हस्ताक्षर और सहेजी गई कस्टम ब्रह्मांड समयरेखाएं संरक्षित क्लाउड डेटाबेस वॉल्ट के भीतर सुरक्षित रूप से मैप की गई हैं। हम आपकी पहचान वेक्टर डेटा को किसी भी कॉर्पोरेट तीसरे पक्ष के नेटवर्क या विश्लेषण इंजनों को बेचते, व्यापार या वितरित नहीं करते हैं।"
    },
    "日本語 (Japanese)": {
        "tab_explore": "🌐 タイムライン探索", "tab_my_creations": "📂 マイユニバース", "tab_create": "🚀 世界の創造", "tab_avatars": "🎭 コミュニティ共同体", "tab_profile": "🔑 アカウントプロファイル", "status_control": "📡 ステータス管理",
        "form_title": "### ⚔️ 世界設計アーキテクトフォーム", "form_subtitle": "物語 of シードを初期化する前に、カスタムタイムラインの根本的なメカニズムを調整します。",
        "lbl_celestial": "##### 🪐 天体物理学パラメーター", "lbl_name": "世界・固有名称:", "lbl_genre": "テーマジャンル選択:", "lbl_gravity": "🪐 重力係数", "lbl_atmosphere": "💨 大気濃度レイヤー",
        "lbl_identity": "##### 🎭 キャラクター固有アイデンティティ", "lbl_char_name": "プレイヤーキャラクター名:", "lbl_backstory": "キャラクタープロファイル/背景設定:",
        "lbl_factions": "##### 🦅 勢力アーキテクチャ & 摩擦対立エレメント", "lbl_allies": "🦅 支配勢力 / 同盟クラン名称", "lbl_enemies": "💀 反乱勢力 / 敵対組織名称", "lbl_directives": "✍️ 固有環境指令 / 世界の制約・ルール",
        "btn_deploy": "🚀 世界線構築エンジン点火", "msg_success": "🎉 カスタムタイムラインの構築に成功しました！",
        "genres": ["SF", "ダークファンタジー", "サイバーパンク", "ホラー", "ロマンス", "その他"],
        "atmosphere_options": ["真空 (宇宙)", "希薄 / 有毒", "標準呼吸可能環境", "超高密度 / 腐食性"],
        "trial_active": "⏳ トライアル有効: 残り {} アクション", "pool_depleted": "🔒 アクションプールが枯渇しました！", "premium_pilot": "👑 認定プレミアムパイロット: {}",
        "active_records_title": "#### 👥 アクティブなタイムライン記録", "your_identity_title": "##### 👑 あなたの現在のアバター", "allied_dreamers_title": "##### 👥 同盟関係の時空観測者", "empty_ledger": "✨ パブリックレジャーは現在空です。", "signin_prompt": "🔑 アカウントプロファイルからログインしてください。",
        "dreamer_lbl": "観測者... {}", "music_prompt": "🎵 音楽を聴くには世界線に参加してください", "unlimited_actions": "無制限のアクセスを解放しますか？", "btn_signin": "ログイン", "btn_signup": "新規登録", "settings_control": "⚙️ 制御システム", "sub_genre_title": "🌌 タイムラインのバリアントを選択", "community_timeline_title": "📜 パブリックコミュニティタイムライン", "btn_join_world": "⚡ この世界線にダイブする",
        "auth_title": "### 🔑 セキュア身元認証ポータル", "auth_subtitle": "プロファイルを認証します。",
        "lbl_email": "メールアドレス:", "lbl_pass": "安全なパスワード:", "btn_login_submit": "🔐 セッション接続を承認", "btn_register_submit": "🚀 新規観測者アイデンティティを鍛造",
        "sub_genres_lbls": ["SF", "ダークファンタジー", "サイバーパンク", "ホラー", "ロマンス", "その他"],
        "btn_launch_scenario": "🎮 シナリオを起動",
        "settings_sub_status_title": "💳 サブスクリプションステータス",
        "settings_status_free": "⏳ ステータス: 無料トライアルモード (残り12アクション)",
        "settings_resync_title": "📡 過去の購入を再同期",
        "settings_resync_desc": "機種変更または再インストールしましたか？以下をタップしてStripeをスキャンし、アクティブな課金サイクルアカウントを確認します。",
        "settings_footer": "Haymaker Industry セキュリティアーキテクチャ v1.02 • プライバシーフレームワーク保護",
        "hub_title": "🪐 Haymaker Industry 総合ハブ",
        "hub_subtitle": "仮想現実を探索、またはあなた自身のタイムラインを構築",
        "profile_sync_lbl": "👑 センキュアなプロファイルが同期されました",
        "btn_logout_sidebar": "🚪 ログアウト",
        "btn_logout_main": "🚪 プラットフォームアカウントからログアウト",
        "forgot_pass_link": "❓ パスワードをお忘れですか？",
        "forgot_pass_desc": "以下にアカウントのメールアドレスを入力すると、安全なパスワード再設定リンクが送信されます。",
        "btn_send_recovery": "🚀 再設定リンクを送信",
        "msg_recovery_sent": "📧 安全な再設定リンクがメールボックスに送信されました。60秒以内に届かない場合は、迷惑メールフォルダを確認してください。",
        "legal_link": "⚖️ 利用規約およびプライバシー保護ポリシー",
        "legal_header": "Haymaker Industry エンドユーザー規約およびプライバシー憲章",
        "legal_sec1_title": "1. 架空のサンドボックス免責事項および絶対的な責任制限",
        "legal_sec1_text": "Haymaker Industryは、実験的、非監視、架空のテキストサンドボックスシミュレータとして厳格に運営されています。すべての物語のテキストストリーム、キャラクターの対話応答、およびイベントの追跡の選択は、100%人工知能の合成生成であり、完全に架空のものです。本プラットフォーム、そのコアコードインフラ、および独立した創設者は、ユーザーの一時的な感情の変動、仮想資産に対する心理的依存、またはサーバーデータの更新に対して一切の責任を負いません。ソフトウェアのメンテナンスは、事前の通知なしにいつでも発生する可能性があり、保存された世界タイムラインの構造的なリセット、劣化、または永久的な消去につながる可能性があります。このペイウォールを通過することにより、ユーザーは当該環境が本質的に不安定であることを認め、自身の心理的境界に対するすべての責任を受け入れ、独立した創設者に対する法的請求または損害賠償を追求するすべての権利を明示的に放棄します。",
        "legal_sec2_title": "2. サブスクリプション規約および非返金方針",
        "legal_sec2_text": "安全なStripeゲートウェイを介してクレジットカード決済を送信することにより、定期的な毎週の課金パスサブスクリプションサイクル（選択に応じて$4.99、$10.99、または$19.99）を承認したことになります。世界の初期化シードによって発生する即時の先行OpenAI APIデータストリーミングコストのため、すべてのサブスクリプション取引は最終的なものであり、100%返金不可能です。ユーザーは完全な制御権を保持し、個人の「アカウントプロファイル」タブからいつでも定期的なサイクルを終了できます。",
        "legal_sec3_title": "3. データの暗号化とプロファイルの保持",
        "legal_sec3_text": "私たちはユーザーのプライバシーを尊重し、独立したソフトウェアサンクチュアリマトリックスの下で運営されています。アカウントのメールアドレス、安全に暗号化されたパスワード署名、および保存されたカスタム宇宙タイムラインは、保護されたクラウドデータベースの金庫内に安全にマッピングされています。私たちは、あなたの身元ベクトルデータを第三者の企業ネットワークや分析エンジンに販売、取引、または配布することは一切ありません。"
    },
    "한국어 (Korean)": {
        "tab_explore": "🌐 세계선 탐색", "tab_my_creations": "📂 나의 창작물", "tab_create": "🚀 세계 창조", "tab_avatars": "🎭 커뮤니티 아바타", "tab_profile": "🔑 계정 프로필", "status_control": "📡 상태 제어 센터",
        "form_title": "### ⚔️ 세계 설계 아키텍트 폼", "form_subtitle": "서사 시드를 초기화하기 전에 커스텀 시간선의 기본 메커니즘을 조정하십시오.",
        "lbl_celestial": "##### 🪐 우주 물리학 매개변수", "lbl_name": "세계선 이름:", "lbl_genre": "테마 장르 선택:", "lbl_gravity": "🪐 중력 수치", "lbl_atmosphere": "💨 대기 밀도",
        "lbl_identity": "##### 🎭 캐릭터 신원 설정", "lbl_char_name": "캐릭터 이름:", "lbl_backstory": "캐릭터 프로필:",
        "lbl_factions": "##### 🦅 세력 아키텍처 & 마찰 대립 요소", "lbl_allies": "🦅 지배 세력 진영 이름", "lbl_enemies": "💀 반란 진영 이름", "lbl_directives": "✍️ 커스텀 환경 지침",
        "btn_deploy": "🚀 코어 엔진 배포 및 점화", "msg_success": "🎉 우주 시간선 시드가 성공적으로 컴파일되었습니다!",
        "genres": ["SF", "다크 판타지", "사이버펑크", "공포", "로맨스", "기타"],
        "atmosphere_options": ["진공 (우주)", "희박 / 유독", "호흡 가능 기준선", "초고밀도 / 부식성"],
        "trial_active": "⏳ 체험판 활성화: {}회 작업 남음", "pool_depleted": "🔒 작업 풀이 모두 소진되었습니다!", "premium_pilot": "👑 인증된 프리미엄 파일럿: {}",
        "active_records_title": "#### 👥 활성화된 커뮤니티 기록", "your_identity_title": "##### 👑 현재 활성화된 아바타", "allied_dreamers_title": "##### 👥 동맹 시간선의 관측자들", "empty_ledger": "✨ 공개 장부가 비어 있습니다.", "signin_prompt": "🔑 로그인 후 실시간 캐릭터 자산을 확인하세요.",
        "dreamer_lbl": "관측자... {}", "music_prompt": "🎵 음악을 들으려면 세계선에 참여하세요", "unlimited_actions": "무제한 작업을 원하십니까?", "btn_signin": "로그인", "btn_signup": "회원가입", "settings_control": "⚙️ 설정 제어", "sub_genre_title": "🌌 시간선 변체 선택", "community_timeline_title": "📜 공개 타임라인", "btn_join_world": "⚡ 이 세계선으로 진입",
        "auth_title": "### 🔑 보안 신원 인증 포털", "auth_subtitle": "프로필을 인증하십시오.",
        "lbl_email": "계정 이메일:", "lbl_pass": "보안 비밀번호:", "btn_login_submit": "🔐 통로 세션 승인", "btn_register_submit": "🚀 새로운 신원 생성",
        "sub_genres_lbls": ["SF", "다크 판타지", "사이버펑크", "공포", "로맨스", "기타"],
        "btn_launch_scenario": "🎮 시나리오 시작",
        "settings_sub_status_title": "💳 구독 상태",
        "settings_status_free": "⏳ 상태: 무료 체험 모드 (12회 남음)",
        "settings_resync_title": "📡 과거 구매 내역 재동기화",
        "settings_resync_desc": "휴대폰을 변경했거나 재설치하셨나요? 아래를 탭하여 Stripe에서 활성 결제 주기 계정 프로필을 스캔하세요.",
        "settings_footer": "Haymaker Industry 보안 아키텍처 v1.02 • 개인정보 보호 프레임워크 적용",
        "hub_title": "🪐 Haymaker Industry 중앙 허브",
        "hub_subtitle": "가상 현실을 탐색하거나 자신만의 시간선을 구축하십시오",
        "profile_sync_lbl": "👑 보안 프로필이 동기화되었습니다",
        "btn_logout_sidebar": "🚪 로그아웃",
        "btn_logout_main": "🚪 플랫폼 계정에서 로그아웃",
        "forgot_pass_link": "❓ 비밀번호를 잊으셨나요?",
        "forgot_pass_desc": "보안 비밀번호 재설정 링크를 받으려면 아래에 계정 이메일을 입력하십시오.",
        "btn_send_recovery": "🚀 재설정 링크 전송",
        "msg_recovery_sent": "📧 보안 재설정 링크가 편지함으로 발송되었습니다! 60초 이내에 도착하지 않으면 스팸 메함 폴더를 확인하십시오.",
        "legal_link": "⚖️ 서비스 약관 및 개인정보 보호정책",
        "legal_header": "Haymaker Industry 최종 사용자 약관 및 개인정보 보호 헌장",
        "legal_sec1_title": "1. 가상 샌드박스 면책 조항 및 절대적 책임 제한",
        "legal_sec1_text": "Haymaker Industry는 엄격히 실험적이고 모니터링되지 않는 가상의 텍스트 샌드박스 시뮬레이터로 운영されます. 모든 서사 텍스트 스트림, 캐릭터 대화 응답 및 이벤트 추적 선택은 100% 인공지능 합성 생성물이며 완전히 허구입니다. 본 플랫폼, 핵심 코드 인프라 및 독립 개발자는 사용자의 일시적인 감정적 동요, 가상 자산에 대한 심리적 애착 또는 서버 데이터 업데이트에 대해 절대적으로 어떠한 책임도 지지 않습니다. 소프트웨어 유지보수는 사전 예고 없이 언제든지 발생할 수 있으며, 이로 인해 저장된 세계 시간선이 구조적으로 재설정, 열화 또는 영구적으로 삭제될 수 있습니다. 이 결제창을 통과함으로써 사용자는 이 환경이 본질적으로 불안정하다는 점을 인정하고 자신의 심리적 경계에 대한 모든 책임을 수용하며, 독립 창립자를 상대로 법적 청구 및 손해 배상을 추구할 모든 권리를 명시적으로 포기합니다.",
        "legal_sec2_title": "2. 구독 약관 및 환불 불가 정책",
        "legal_sec2_text": "보안 Stripe 게이트웨이를 통해 신용카드 결제를 제출함으로써 귀하는 정기적인 주간 결제 패스 구독 주기(선택에 따라 $4.99, $10.99 또는 $19.99)를 승인하게 됩니다. 세계 초기화 시드로 인해 즉각적인 선행 OpenAI API 데이터 스트리밍 비용이 발생하므로 모든 구독 거래는 최종적이며 100% 환불이 불가능합니다. 사용자는 완전한 제어권을 보유하며 언제든지 개인 계정 프로필 탭을 통해 정기 구독 주기를 종료할 수 있습니다.",
        "legal_sec3_title": "3. 데이터 암호화 및 프로필 보존",
        "legal_sec3_text": "우리는 사용자의 개인정보를 존중하며 독립적인 소프트웨어 보호 매트릭스 하에서 운영됩니다. 귀하의 계정 이메일 주소, 안전하게 암호화된 비밀번호 서명 및 저장된 커스텀 우주 시간선은 보호된 클라우드 데이터베이스 보관함 내에 안전하게 매핑됩니다. 우리는 귀하의 신원 벡터 데이터를 제3의 기업 네트워크나 분석 엔진에 판매, 거래 또는 배포하지 않습니다."
    },
    "Português (Portuguese)": {
        "tab_explore": "🌐 Explorar Universos", "tab_my_creations": "📂 Minhas Criações", "tab_create": "🚀 Criar um Mundo", "tab_avatars": "🎭 Avatares da Comunidade", "tab_profile": "🔑 Perfil de Conta", "status_control": "📡 CONTROLE DE STATUS",
        "form_title": "### ⚔️ Formulário do Arquiteto do Universo", "form_subtitle": "Ajuste a mecânica fundamental da sua linha do tempo antes de inicializar a semente narrativa.",
        "lbl_celestial": "##### 🪐 Física Celestial", "lbl_name": "Nome do Universo:", "lbl_genre": "Selecione o gênero temático:", "lbl_gravity": "🪐 Níveis de Gravidade", "lbl_atmosphere": "💨 Densidade Atmosférica",
        "lbl_identity": "##### 🎭 Configuração de Identidade do Personagem", "lbl_char_name": "Nome do seu personagem:", "lbl_backstory": "Perfil/Histórico do personagem:",
        "lbl_factions": "##### 🦅 Arquitetura de Facções e Elementos de Fricção", "lbl_allies": "🦅 Nome da Facção Dominante / Aliada", "lbl_enemies": "💀 Nome da Facção Rebelde / Inimiga", "lbl_directives": "✍️ Diretrizes / Restrições Ambientais Personalizadas",
        "btn_deploy": "🚀 Implantar e Acender o Motor Central", "msg_success": "🎉 Semente da linha do tempo do universo compilada com sucesso!",
        "genres": ["Ficção Científica", "Fantasia Sombria", "Cyberpunk", "Terror", "Romance", "Outro"],
        "atmosphere_options": ["Vácuo (Espaço)", "Rara / Tóxica", "Linha de Base Respirável", "Hipertensa / Corrosiva"],
        "trial_active": "⏳ TESTE ATIVO: {} Ações Restantes", "pool_depleted": "🔒 Pool de Ações Esgotado!", "premium_pilot": "👑 PILOTO PREMIUM AUTENTICADO: {}",
        "active_records_title": "#### 👥 Registros Ativos da Comunidade", "your_identity_title": "##### 👑 SUA IDENTIDADE ATIVA FORJADA", "allied_dreamers_title": "##### 👥 SONHADORES DE LINHAS DO TEMPO ALIADAS", "empty_ledger": "✨ O registro público está atualmente vazio. Seja o primeiro a forjar uma identidade acima!", "signin_prompt": "🔑 Por favor, faça login na aba 'Perfil de Conta' para ver os registros dos personagens ao vivo.",
        "dreamer_lbl": "Sonhador... {}", "music_prompt": "🎵 Para ouvir música, junte-se ou forje uma linha do tempo mundial", "unlimited_actions": "Quer ações ilimitadas?", "btn_signin": "Entrar", "btn_signup": "Cadastrar-se", "settings_control": "⚙️ Controle de Configurações", "sub_genre_title": "🌌 Selecione Sua Variante de Linha do Tempo", "community_timeline_title": "📜 Linha do Tempo Pública da Comunidade", "btn_join_world": "⚡ Entrar Neste Universo da Comunidade",
        "auth_title": "### 🔑 Portal de Identificação Secure", "auth_subtitle": "Autorize seu nó de identidade de perfil para salvar linhas do tempo personalizadas.",
        "lbl_email": "E-mail da Conta:", "lbl_pass": "Senha de Segurança:", "btn_login_submit": "🔐 Autorizar Sessão", "btn_register_submit": "🚀 Forjar Nova Identidade de Perfil",
        "sub_genres_lbls": ["Ficção Científica", "Fantasia Sombria", "Cyberpunk", "Terror", "Romance", "Outro"],
        "btn_launch_scenario": "🎮 Iniciar Cenário",
        "settings_sub_status_title": "💳 Status da Assinatura",
        "settings_status_free": "⏳ STATUS: Modo de Teste Gratuitos (12 Ações)",
        "settings_resync_title": "📡 Re-sincronizar Compras Passadas",
        "settings_resync_desc": "Mudou de telefone ou reinstalou? Toque abaixo para escanear o Stripe em busca de perfis de conta com ciclo de faturamento ativo.",
        "settings_footer": "Arquitetura de Segurança da Haymaker Industry v1.02 • Estrutura de Privacidade Protegida.",
        "hub_title": "🪐 Hub Central da Haymaker Industry",
        "hub_subtitle": "Explore realidades alternativas ou forje a sua própria linha do tempo",
        "profile_sync_lbl": "👑 Perfil Seguro Sincronizado",
        "btn_logout_sidebar": "🚪 Sair",
        "btn_logout_main": "🚪 Sair da Conta da Plataforma",
        "forgot_pass_link": "❓ Esqueceu a senha?",
        "forgot_pass_desc": "Insira o e-mail da sua conta abaixo para receber um link seguro de redefinição de senha.",
        "btn_send_recovery": "🚀 Enviar Link de Redefinição",
        "msg_recovery_sent": "📧 Um link de redefinição seguro foi enviado para sua caixa de entrada! Verifique sua pasta de spam se não chegar em 60 segundos.",
        "legal_link": "⚖️ Termos de Serviço e Política de Proteção de Privacidade",
        "legal_header": "Termos de Usuário Final e Estatuto de Privacidade da Haymaker Industry",
        "legal_sec1_title": "1. Renúncia de Sandbox Fictício e Limitação Absoluta de Responsabilidade",
        "legal_sec1_text": "A Haymaker Industry funciona estritamente como um simulador experimental, não monitorado e fictício de sandbox de texto. Todas as transmissões de texto narrativo, respostas de diálogo de personagens e escolhas de rastreamento de eventos são 100% geração sintética de IA e totalmente fictícias. A plataforma, sua infraestrutura de código central e seu fundador independente não assumem absolutamente nenhuma responsabilidade por sofrimento emocional do usuário, apego psicológico a ativos fictícios ou atualizações de dados do servidor. A manutenção do software pode ocorrer a qualquer momento sem aviso prévio, o que pode resultar na redefinição estrutural, degradação ou exclusão permanente de linhas do tempo mundiais salvas. Ao passar por este paywall, o usuário reconhece que este ambiente é intrinsecamente instável, aceita total responsabilidade por seus limites psicológicos e renuncia explicitamente a todos os direitos de buscar reivindicações legais ou danos contra o fundador independente.",
        "legal_sec2_title": "2. Termos de Assinatura e Não Reembolso de Capital",
        "legal_sec2_text": "Ao enviar um pagamento com cartão de crédito por meio de nossa pasarela segura do Stripe, você está autorizando um ciclo de assinatura de passe de faturamento semanal recorrente ($4.99, $10.99 ou $19.99 com base em sua seleção). Devido aos custos imediatos e antecipados de streaming de datos da API OpenAI gerados pelas sementes de inicialização do mundo, todas as transações de assinatura são definitivas e 100% não reembolsáveis. Os usuários mantêm o controle total e podem encerrar seu ciclo recorrente por meio de sua aba Perfil de Conta pessoal a qualquer momento.",
        "legal_sec3_title": "3. Criptografia de Dados e Retenção de Perfil",
        "legal_sec3_text": "Respeitamos a privacidade do usuário e operamos sob uma matriz de santuário de software independente. O endereço de e-mail da sua conta, a assinatura de senha criptografada segura e as linhas do tempo salvas do universo personalizado são mapeados de forma segura dentro de cofres de banco de dados protegidos na nuvem. Não vendemos, comercializamos ou distribuímos seus dados de vetor de identidade para redes corporativas de terceiros ou mecanismos de análise."
    }
}) # 🚨 MASTER DICTIONARY VAULT UPDATE SECURELY CLOSED AND PINNED
# 🔒 EXTRA RE-SYNC AND PREMIUM PAYWALL KEY INJECTIONS
LOCALIZATION_VAULT["Русский (Russian)"].update({
    "paywall_title": "🔒 Бесплатные действия закончились",
    "paywall_subtitle": "Выберите пропуск, чтобы продолжить исследовать миры.",
    "paywall_login": "Создайте бесплатный аккаунт или войдите, чтобы продолжить и открыть доступ.",
    "tier1_name": "Пропуск «Аватар»",
    "tier1_desc": "Безлимитные действия во всех мирах и надёжная память истории.",
    "tier2_name": "Пропуск «Спартанец»",
    "tier2_desc": "Всё из «Аватара» плюс более долгая память истории для многочасовых приключений.",
    "tier3_name": "Пропуск «Титан»",
    "tier3_desc": "Всё из «Спартанца», самая долгая память истории и ранний доступ к новым функциям.",
    "btn_activate": "Активировать пропуск",
    "legal_compliance_link": "⚖️ Условия использования и политика конфиденциальности",
    "per_week": "/ нед.",
})

LOCALIZATION_VAULT["Français (French)"].update({
    "paywall_title": "🔒 Vos actions gratuites sont épuisées",
    "paywall_subtitle": "Choisissez un pass pour continuer à explorer.",
    "paywall_login": "Créez un compte gratuit ou connectez-vous pour continuer et débloquer un pass.",
    "tier1_name": "Pass Avatar",
    "tier1_desc": "Actions illimitées dans tous les mondes, avec une bonne mémoire d'histoire.",
    "tier2_name": "Pass Spartan",
    "tier2_desc": "Tout le Pass Avatar, plus une mémoire d'histoire plus longue pour des aventures de plusieurs heures.",
    "tier3_name": "Pass Titan",
    "tier3_desc": "Tout le Pass Spartan, avec la plus longue mémoire d'histoire et un accès anticipé aux nouveautés.",
    "btn_activate": "Activer le pass",
    "legal_compliance_link": "⚖️ Conditions d'utilisation et politique de confidentialité",
    "per_week": "/ sem.",
})

LOCALIZATION_VAULT["العربية (Arabic)"].update({
    "paywall_title": "🔒 انتهت إجراءاتك المجانية",
    "paywall_subtitle": "اختر باقة لمواصلة الاستكشاف.",
    "paywall_login": "أنشئ حسابًا مجانيًا أو سجّل الدخول للمتابعة وفتح باقة.",
    "tier1_name": "باقة أفاتار",
    "tier1_desc": "إجراءات غير محدودة في جميع العوالم مع ذاكرة قصة جيدة.",
    "tier2_name": "باقة سبارتان",
    "tier2_desc": "كل ما في باقة أفاتار، بالإضافة إلى ذاكرة قصة أطول لمغامرات تمتد لساعات.",
    "tier3_name": "باقة تايتن",
    "tier3_desc": "كل ما في باقة سبارتان، مع أطول ذاكرة قصة ووصول مبكر إلى الميزات الجديدة.",
    "btn_activate": "تفعيل الباقة",
    "legal_compliance_link": "⚖️ شروط الخدمة وسياسة الخصوصية",
    "per_week": "/ أسبوعيًا",
})

LOCALIZATION_VAULT["हिन्दी (Hindi)"].update({
    "paywall_title": "🔒 आपके मुफ़्त एक्शन समाप्त हो गए हैं",
    "paywall_subtitle": "खोज जारी रखने के लिए एक पास चुनें।",
    "paywall_login": "जारी रखने... और पास अनलॉक करने के लिए मुफ़्त खाता बनाएँ या लॉग इन करें।",
    "tier1_name": "अवतार पास",
    "tier1_desc": "सभी दुनियाओं में असीमित एक्शन, साथ में भरोसेमंद कहानी-स्मृति।",
    "tier2_name": "स्पार्टन पास",
    "tier2_desc": "अवतार पास की सभी सुविधाएँ, साथ में घंटों लंबे रोमांच के लिए ज़्यादा लंबी कहानी-स्मृति।",
    "tier3_name": "टाइटन पास",
    "tier3_desc": "स्पार्टन पास की सभी सुविधाएँ, सबसे लंबी कहानी-स्मृति और नई सुविधाओं तक जल्दी पहुँच।",
    "btn_activate": "पास सक्रिय करें",
    "legal_compliance_link": "⚖️ सेवा की शर्तें और गोपनीयता नीति",
    "per_week": "/ सप्ताह",
})

LOCALIZATION_VAULT["日本語 (Japanese)"].update({
    "paywall_title": "🔒 無料アクションを使い切りました",
    "paywall_subtitle": "冒険を続けるには、パスを選んでください。",
    "paywall_login": "続行してパスを利用するには、無料アカウントを作成するかログインしてください。",
    "tier1_name": "アバターパス",
    "tier1_desc": "すべての世界で無制限にアクションでき、しっかりとしたストーリーメモリー付き。",
    "tier2_name": "スパルタンパス",
    "tier2_desc": "アバターパスの全機能に加え、数時間におよぶ冒険に対応する、より長いストーリーメモリー。",
    "tier3_name": "タイタンパス",
    "tier3_desc": "スパルタンパスの全機能に加え、最本のストーリーメモリーと新機能の先行アクセス。",
    "btn_activate": "パスを有効にする",
    "legal_compliance_link": "⚖️ 利用規約とプライバシーポリシー",
    "per_week": "/ 週",
})

LOCALIZATION_VAULT["한국어 (Korean)"].update({
    "paywall_title": "🔒 무료 액션을 모두 사용했습니다",
    "paywall_subtitle": "계속 탐험하려면 이용권을 선택하세요.",
    "paywall_login": "계속하고 이용권을 사용하려면 무료 계정을 만들거나 로그인하세요.",
    "tier1_name": "아바타 패스",
    "tier1_desc": "모든 월드에서 무제한 액션과 안정적인 스토리 메모리를 제공합니다.",
    "tier2_name": "스파르탄 패스",
    "tier2_desc": "아바타 패스의 모든 혜택에 더해, 몇 시간짜리 모험을 위한 더 긴 스토리 메모리.",
    "tier3_name": "타이탄 패스",
    "tier3_desc": "스파르탄 패스의 모든 혜택에 더해, 가장 긴 스토리 메모리와 신기능 우선 체험.",
    "btn_activate": "패스 활성화",
    "legal_compliance_link": "⚖️ 이용약관 및 개인정보 처리방침",
    "per_week": "/ 주",
})

LOCALIZATION_VAULT["Português (Portuguese)"].update({
    "paywall_title": "🔒 Suas ações gratuitas acabaram",
    "paywall_subtitle": "Escolha um passe para continuar explorando.",
    "paywall_login": "Crie uma conta gratuita ou entre para continuar e desbloquear um passe.",
    "tier1_name": "Passe Avatar",
    "tier1_desc": "Ações ilimitadas em todos os mundos, com uma boa memória de história.",
    "tier2_name": "Passe Spartan",
    "tier2_desc": "Tudo do Passe Avatar, mais uma memória de história maior para aventuras de várias horas.",
    "tier3_name": "Passe Titan",
    "tier3_desc": "Tudo do Passe Spartan, com a maior memória de história e acesso antecipado a novidades.",
    "btn_activate": "Ativar passe",
    "legal_compliance_link": "⚖️ Termos de Serviço e Política de Privacidade",
    "per_week": "/ sem.",
})
# 🌐 MASTER CORE PAYWALL INTEGRATIONS (ENGLISH, SPANISH, MANDARIN SUB-SETS)
LOCALIZATION_VAULT["English"].update({
    "paywall_title": "🔒 Your free actions are used up",
    "paywall_subtitle": "Choose a pass to keep exploring.",
    "paywall_login": "Create a free account or log in to continue and unlock a pass.",
    "tier1_name": "Avatar Pass",
    "tier1_desc": "Unlimited actions across every world, with a solid story memory.",
    "tier2_name": "Spartan Pass",
    "tier2_desc": "Everything in Avatar, plus a longer story memory for multi-hour adventures.",
    "tier3_name": "Titan Pass",
    "tier3_desc": "Everything in Spartan, with the longest story memory and early access to new features.",
    "btn_activate": "Activate Pass",
    "legal_compliance_link": "⚖️ Terms of Service & Privacy Policy",
    "per_week": "/ wk",
})

LOCALIZATION_VAULT["Español (Spanish)"].update({
    "paywall_title": "🔒 Tus acciones gratuitas se agotaron",
    "paywall_subtitle": "Elige un pase para seguir explorando.",
    "paywall_login": "Crea una cuenta gratuita o inicia sesión para continuar y desbloquear un pase.",
    "tier1_name": "Pase Avatar",
    "tier1_desc": "Acciones ilimitadas en todos los mundos, con uma buena memoria de historia.",
    "tier2_name": "Pase Spartan",
    "tier2_desc": "Todo el Pase Avatar, más una memoria de historia más larga para aventuras de varias horas.",
    "tier3_name": "Pase Titan",
    "tier3_desc": "Todo el Pase Spartan, con la memoria de historia más larga y acceso anticipado a novedades.",
    "btn_activate": "Activar pase",
    "legal_compliance_link": "⚖️ Términos de Servicio y Política de Privacidad",
    "per_week": "/ sem",
})

LOCALIZATION_VAULT["简体中文 (Mandarin)"].update({
    "paywall_title": "🔒 您的免费次数已用完",
    "paywall_subtitle": "请选择一个通行证以继续探索。",
    "paywall_login": "创建免费账户或登录以继续并解锁通行证。",
    "tier1_name": "化身通行证",
    "tier1_desc": "所有世界无限行动，并配备可靠的故事记忆。",
    "tier2_name": "斯巴达通行证",
    "tier2_desc": "包含化身通行证的全部权益，并提供更长的故事记忆，适合数小时的冒险。",
    "tier3_name": "泰坦通行证",
    "tier3_desc": "包含斯巴达通行证의 전부 권익, 유구한 고사 기억 구비, 신기능 선행 체험 가능.",
    "btn_activate": "激活通行证",
    "legal_compliance_link": "⚖️ 服务条款与隐私政策",
    "per_week": "/ 周",
})
